version: '3'
services:
  nginx:
    #    image: 'nginx:latest'
    build: ./docker/nginx/
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ./:/platform
    - ./storage/nginx/main:/etc/nginx/conf.d
    - ./docker/nginx/certs/edu-selfsigned.crt:/etc/ssl/certs/edu-selfsigned.crt
    - ./docker/nginx/certs/edu-selfsigned.key:/etc/ssl/private/edu-selfsigned.key
    networks:
    - frontend
    - backend
    - user_apps_net
    - docker
  #    restart: always
  core:
    build: ./docker/php/
    volumes:
    - ./:/platform
    environment:
    - DOCKER_HOST=tcp://docker:2375
    networks:
    - backend
    - docker
  #    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=edu
    volumes:
    - ~/db/mysql:/var/lib/mysql
    ports:
    - 3306:3306
    networks:
    - backend
  # docker in docker
  docker:
    image: docker:dind
    privileged: true
    command: --storage-driver=vfs
    volumes:
    - ./storage:/storage
    - ./dind:/dind
    networks:
    - docker
  # docker manager UI
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    ports:
    - '9000:9000'
networks:
  frontend:
  backend:
  docker:
  user_apps_net:
volumes:
  portainer_data:
