version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ./:/platform
    - ./docker/nginx/confs:/etc/nginx/conf.d:ro
    - ./docker/nginx/certs/edu-selfsigned.crt:/etc/ssl/certs/edu-selfsigned.crt:ro
    - ./docker/nginx/certs/edu-selfsigned.key:/etc/ssl/private/edu-selfsigned.key:ro
    - ./logs/core/core-error.log:/var/log/nginx/core-error.log
    - ./logs/evklid-error.log:/var/log/nginx/evklid-error.log
    networks:
    - frontend
    - backend
    - user_apps_net
    - docker
    restart: always
    depends_on:
      - core
      - evklid
      - dind
  core:
    build: ./docker/php/
    volumes:
    - ./:/platform
    environment:
    - DOCKER_HOST=tcp://dind:2375
    - PHP_IDE_CONFIG=serverName=docker
    - PHP_XDEBUG_ENABLED=1
    - XDEBUG_CONFIG=remote_host=10.254.254.254
    networks:
    - backend
    - docker
    restart: always
  mysql:
    image: mysql/mysql-server
    container_name: mysql_db
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=edu
    - MYSQL_ROOT_HOST=%
    volumes:
      - ~/db/mysql/core:/var/lib/mysql # Данные платформы
      - ./docker/mysql/my.cnf:/etc/my.cnf
    ports:
    - 3306:3306
    networks:
    - backend
  # docker in docker
  dind:
    build: ./docker/dind/
    privileged: true
    command: --storage-driver=vfs
    volumes:
    - ./storage:/storage
    - ./dind:/dind
    - ~/db/mysql/user_apps:/db/mysql_apps
    ports:
    - 3307:3307
    networks:
    - docker
  cleaner:
    build: ./docker/cleaner
    environment:
    - DOCKER_HOST=tcp://dind:2375
    networks:
    - docker
  # Evklid trainer
  evklid:
    build: ./docker/default_apps/evklid-trainer/
    depends_on:
      - mongo
    networks:
      - user_apps_net
      - docker
  mongo:
    container_name: mongo
    image: mongo:3.2
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - user_apps_net
      - docker
    volumes:
      - ~/db/mongo/default_apps:/data/db # Данные тренажера Евклида
networks:
  frontend:
  backend:
  docker:
  user_apps_net:
