version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ./:/platform
    - ./docker/nginx/confs:/etc/nginx/conf.d
    - ./docker/nginx/certs/edu-selfsigned.crt:/etc/ssl/certs/edu-selfsigned.crt
    - ./docker/nginx/certs/edu-selfsigned.key:/etc/ssl/private/edu-selfsigned.key
    - ./logs/core/core-error.log:/var/log/nginx/core-error.log
    networks:
    - frontend
    - backend
    - user_apps_net
    - docker
    restart: always
  core:
    build: ./docker/php/
    volumes:
    - ./:/platform
    environment:
    - DOCKER_HOST=tcp://dind:2375
    - PHP_IDE_CONFIG=serverName=docker
    - PHP_XDEBUG_ENABLED=1
    - XDEBUG_CONFIG=remote_host=10.254.254.254
    networks:
    - backend
    - docker
  #    restart: always
  mysql:
    image: mysql/mysql-server
    container_name: mysql_db
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=edu
    - MYSQL_ROOT_HOST=%
    volumes:
    - ~/db/mysql/core:/var/lib/mysql
    - ./docker/mysql/my.cnf:/etc/my.cnf
    ports:
    - 3306:3306
    networks:
    - backend
  # docker in docker
  dind:
    image: docker:dind
    privileged: true
    command: --storage-driver=vfs
    volumes:
    - ./storage:/storage
    - ./dind:/dind
    - ~/db/mysql/user_apps:/db/mysql_apps
    ports:
    - 3307:3307
    networks:
    - docker
  cleaner:
    build: ./docker/cleaner
    environment:
    - DOCKER_HOST=tcp://dind:2375
    networks:
    - docker
  # docker manager UI
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    ports:
    - '9999:9000'
networks:
  frontend:
  backend:
  docker:
  user_apps_net:
volumes:
  portainer_data:
