version: '2'
services:
    nginx: { build: ./docker/nginx/, volumes: ['/storage/user_confs:/etc/nginx/conf.d/user_confs', '/storage/user_logs:/var/user_logs', '/storage/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro', '/storage/user_apps:/usr/share/nginx/html'], ports: ['80:80'], restart: always }
    mysql: { image: mysql/mysql-server, environment: [MYSQL_ROOT_PASSWORD=password, MYSQL_DATABASE=apps, MYSQL_ROOT_HOST=%], volumes: ['/storage/docker/mysql/my.cnf:/etc/my.cnf'], ports: ['3307:3306'] }
    portainer: { image: portainer/portainer, command: '-H unix:///var/run/docker.sock', volumes: ['/var/run/docker.sock:/var/run/docker.sock', 'portainer_data:/data'] }
volumes:
    portainer_data: null
