<?php
/**
 * Created by PhpStorm.
 * User: dmitriy
 * Date: 09.10.18
 * Time: 15:57
 */

namespace api\modules\v1;


use yii\filters\auth\HttpBearerAuth;
use yii\rest\Controller;

class AppController extends Controller
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
        ];
        return $behaviors;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->user->enableSession = false;
    }

    public function actionIndex()
    {
        return 'api/app';
    }

    public function actionStart()
    {

    }
}
